SAP/sap-btp-service-operator

main.go, sapbtp-operator-charts/templates/deployment.yml
=> add liveness probe

sapbtp-operator-charts/templates/deployment.yml, sapbtp-operator-charts/values.yaml
The security context will allow to harden the permissions on the pod - e.g. to set runAsNonRoot.
=> [WIP]feat: add support for securityContext

api/v1/webhooks/servicebinding_mutating_webhook.go, api/v1/webhooks/serviceinstance_mutating_webhook.go, controllers/servicebinding_controller.go, controllers/serviceinstance_controller.go
add finalizers in controller rather than in admission webhook
=> add finalizers in controller

controllers/controller_util.go, controllers/controller_util_test.go, controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go
add .metadata to binding secret which describes the credentials + metadata property types
=> add metadata to binding secrets

controllers/servicebinding_controller.go, controllers/serviceinstance_controller.go
=> fix nil pointer when last operation is not available

controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go, controllers/serviceinstance_controller.go, controllers/serviceinstance_controller_test.go
=> bug fix when last operation not exist

sapbtp-operator-charts/templates/deployment.yml
Added option to define node selector and tolerations config cases
=> Added node selector and tolerations config cases

controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go
=> support long binding names

README.md, api/common.go, api/v1/servicebinding_validating_webhook.go, api/v1/servicebinding_validating_webhook_test.go, api/v1/webhooks/servicebinding_mutating_webhook.go, controllers/base_controller.go, controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go
=> fix credentials rotation - avoid deleting stale binding if rotation failed

controllers/base_controller.go
In some cases Service Manger might return 429 response, this is a temporary error and should not be reflected to the user.
=> handle too many requests

config/rbac/auth_proxy_role_binding.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, sapbtp-operator-charts/templates/crd.yml, sapbtp-operator-charts/templates/deployment.yml, sapbtp-operator-charts/templates/rbac.yml, sapbtp-operator-charts/templates/service_account.yaml
=> use dedicated service account

README.md
=> update readme regarding the pre delete

.github/workflows/release.yml
=> fix tag issue in release

sapbtp-operator-charts/templates/pre-delete-job.yml, sapbtp-operator-charts/values.yaml
There is no option to override the pre-delete-job image from values. We have a corporate scenario which requires pulling images from the corporate repository
Extracting the image url to values allows override
If you use third …
=> fix: extract pre-delete-job image to values

sapbtp-operator-charts/values.yaml
=> Update rbac image

client/sm/types/types.go, controllers/serviceinstance_controller.go, controllers/serviceinstance_controller_test.go
fix description for failed async op
=> fix description for failed async op

controllers/serviceinstance_controller.go, controllers/serviceinstance_controller_test.go
=> Bug fix - avoid update instance when not required

controllers/base_controller.go, controllers/serviceinstance_controller.go, controllers/serviceinstance_controller_test.go
first check delete check operation.url
=> Allow delete while "create in progress"

Dockerfile
better go version for the vulnerabilities scanner results
=> better go version

api/v1/serviceinstance_types.go, client/sm/client.go, client/sm/suite_test.go, controllers/base_controller.go, controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go, controllers/serviceinstance_controller.go, controllers/serviceinstance_controller_test.go, controllers/suite_test.go
fix tests:
1. Remove all conditions[x] from tests
2. Create functions for common code
3. Remove (almost) all justBefore / justAfter 
4. Fix tests that did not check properly
5. Wrap with eventually any crud operation
6. Remove generation from shared condition
=> Test improvements

api/common.go, controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go
Use instance.external_name in secret.instance_name
=> Use instance.external_name in secret.instance_name

controllers/base_controller.go, controllers/suite_test.go
=> FIX - handle create binding transient error when instance not exist

Dockerfile, controllers/serviceinstance_controller.go
=> include async operation description in status

Dockerfile, controllers/serviceinstance_controller.go
=> Fix description log

controllers/base_controller.go, controllers/servicebinding_controller.go, controllers/serviceinstance_controller.go
rate limit error should not be reflected to the resource's status
=> Handle too many requests error from service-manager

controllers/servicebinding_controller.go
when a binding is created before the corresponding instance it is stuck as blocked and not being retried
=> Bug fix - retry binding reconcile when instance is not found

config/samples/btp_access_credentials_secret.yaml, controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go, sapbtp-operator-charts/templates/crd.yml
while using secret template if no data or stringData is provided, utilize the default secret data.
=> [SAPBTPCFS-3288] secret template with default data structure

README.md
=> Changes to Credentials Rotation.md

api/v1/servicebinding_validating_webhook.go, api/v1/servicebinding_validating_webhook_test.go, controllers/servicebinding_controller_test.go
resolve error "failed to create secret from template	{"error": "the Secret template is invalid"}"
=> Bug fix - secret template cannot be parsed error

main.go
include all service instance and binding in cache in case limited cache is used
=> Limited Cache - include instances and bindings to limited cache

main.go
=> support limited cache when clusterAccess is false

api/common/common.go, api/v1/servicebinding_types.go, api/v1/servicebinding_types_test.go, api/v1/serviceinstance_types.go, api/v1/serviceinstance_types_test.go, api/v1/webhooks/serviceinstance_mutating_webhook.go, controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go, controllers/serviceinstance_controller.go, controllers/serviceinstance_controller_test.go, controllers/suite_test.go, internal/utils/condition_utils.go, internal/utils/condition_utils_test.go
after applying update fro kyma ui it is not possible to update the instance using kubectl
=> bug fix - userInfo cannot be changed error 

sapbtp-operator-charts/templates/configmap.yml, sapbtp-operator-charts/templates/secret.yml, sapbtp-operator-charts/values.yaml
Add support for specifying annotations for secret and configmap through Helm values.
=> custom annotations for operator's configmap and secret

README.md
=> Adding a Note about watchForParametersFromChanges.md

api/v1/types.go, config/crd/bases/services.cloud.sap.com_servicebindings.yaml, config/crd/bases/services.cloud.sap.com_serviceinstances.yaml, internal/utils/parameters.go
=> BUG FIX - controller crash when parameters from contains invalid data 

.github/workflows/go.yml, Dockerfile, go.mod, sapbtp-operator-charts/values.yaml
=> Bump go and rbac proxy version

sapbtp-operator-charts/values.yaml
=> fix rbac version

README.md
=> For Avi to Approve.md

controllers/servicebinding_controller.go, controllers/servicebinding_controller_test.go
add ability to identify stale secret
=> add stale label to stale secret
