- controllers/servicebinding_controller.go
When testing migration of `ServiceInstances`, the operator went to `CrashLoopBackOff`
```
$ k get po -nsap-btp-operator
NAME                                                   READY   STATUS             RESTARTS   AGE
sap-btp-operator-controller-manager-595b76f4f8-xj65c   1/2     CrashLoopBackOff   7          28m
```
logs: [crashloop.log](https://github.com/SAP/sap-btp-service-operator/files/6686850/crashloop.log)
Not sure if this is the best place to address the problem but it has resolved the crashes in our use case.
fixes: https://github.com/SAP/sap-btp-service-operator/issues/58
> Fix CrashLoop when status conditions are empty

- Dockerfile
Hi there,
we are using PodSecurityPolicies to harden our cluster. Among other things, these PSPs mandate that pods do not run as root.
However, the default user in the `controller` image is specified by name (`nonroot`) and thus the admission controller cannot determine if it is root or not (see [K8s sources](https://github.com/kubernetes/kubernetes/blob/5648200571889140ad246feb82c8f80a5946f167/pkg/kubelet/kuberuntime/security_context.go#L92)). 
I'd like to change the Dockerfile so that the default user from the distroless image is referenced by uid and not by name (see [here](https://github.com/GoogleContainerTools/distroless/blob/d1a3d9338121dfe009634c70a28cde51fff7e6c9/base/BUILD#L10)). So this change doesn't change the default user, just how it's referenced.
Thank you!
> Use numerical USER in Dockerfile

- sapbtp-operator-charts/templates/configmap.yml
- sapbtp-operator-charts/templates/deployment.yml
- sapbtp-operator-charts/templates/secret.yml
- sapbtp-operator-charts/values.yaml
This change aims to improve the ability to use the helm chart in GitOps scenarios (focus on ArgoCD but should apply with other tools as well)
Changes in detail:
* `configmap.yml` only lookup the value from the cluster if none is defined in the Helm values. This makes the helm values the leading system
* `deployment.yml` only roll the deployment if something changes in the configmap or the secret (otherwise ArgoCD would always report changes and potentially constantly roll the deployment)
* `secret.yml` the secret contains potentially secret data (it does if clientsecret is specified, arguably it does not if clientsecret is omitted?) and it is therefore desirable to manage it differently when using ArgoCD, for example using sealed secrets. Note: for `secret-tls.yml` this scenario already …
> make helm chart more gitops friendly

- sapbtp-operator-charts/templates/deployment.yml
in PR #110 a change was introduced that broke the templated helm chart, this corrects it again.
Sorry for that, I originally failed in correctly bringing the changes to my fork
> fix broken helm chart

- sapbtp-operator-charts/templates/deployment.yml
- sapbtp-operator-charts/templates/service.yml
* I've deployed BTP operator and the service with only one label selectors pointed to other applications so webhook was not requested when I was applying BTP operator resources
Pods contains labels which identifies only btp operator Pods
This PR fixes the issue: https://github.com/SAP/sap-btp-service-operator/issues/152
> Pods contains proper labels

- sapbtp-operator-charts/templates/deployment.yml
- sapbtp-operator-charts/values.yaml
PR resolves #170 
*add better integrity to the image version, we should provide a way to add a digest option to the operator images this way we can validate the image version*
Add digest option to btp-operator chart, 
By adding a new `sha` field to  the deployment file and concatenate it to the image string address when provided.
If you use third party code …
> Add digest option to btp-operator chart

- hack/kubectl-sapbtp
I don't have the permissions to assign myself to an issue, therefore creating one is pointless.
Calling `kubectl sapbtp <plans|marketplace|services>` fails on Kyma clusters with `curl: (3) Failed to convert e to ACE; could not convert string to UTF-8`, this is because the `sap-btp-service-operator` secret does not contain the `url` property.
Use the `sm_url` property instead
If you use third party code …
> use sm_url instead of url in kubectl plugin

- sapbtp-operator-charts/templates/deployment.yml
Kyma project currently uses fork of BTP Operator helm chart with few custom changes. We would like to upstream all configuration knobs and eventually deprecate the https://github.com/kyma-incubator/sap-btp-service-operator.
This is a first PR containing mainly just configurability for deployment annotations and priority class.
Previous PR https://github.com/SAP/sap-btp-service-operator/pull/201 has been closed without any review or comment and I am unable to reopen it.
> Chart labels, annotations, and priority class config

- client/sm/client.go
- client/sm/client_test.go
- controllers/base_controller.go
- controllers/servicebinding_controller_test.go
- controllers/serviceinstance_controller_test.go
> fix sm response parsing

- README.md
I have encountered that some of the YAML examples in the REAMDE.md have wrong indents. When you copy them over in a separate file, it will cause YAML validation errors. I fixed this now in this PR which will make it more user friendly.
> docs(readme): Fix indents for yaml examples

- api/v1/serviceinstance_validating_webhook.go
- api/v1/serviceinstance_validating_webhook_test.go
- config/samples/services_v1_serviceinstance.yaml
- controllers/base_controller.go
- controllers/servicebinding_controller.go
- controllers/serviceinstance_controller.go
- controllers/serviceinstance_controller_test.go
when upgrading the operator from old releases the operator will send an update request to the broker for instances without status.hashedSpec value even if the instance was not changed, this might lead to an error since there are brokers who does not support updates
> bug fix - avoid instance update if spec not changed

- Dockerfile
- controllers/base_controller.go
provide dedicated error message for invalid sm credentials
> better error message for invalid Service Manager credentials

- controllers/servicebinding_controller.go
- controllers/servicebinding_controller_test.go
when an instance is somehow deleted before the binding, the controller will crash when trying to delete the binding
> Bug fix - delete orphan binding panics

- README.md
need to use stringData for a secret creation like mentioned in the Readme.
> Update README - Fix secret to use stringData instead of data

- main.go
- sapbtp-operator-charts/templates/deployment.yml
- sapbtp-operator-charts/values.yaml
Issue: https://github.com/SAP/sap-btp-service-operator/issues/405
When the log from btp operator is sent to a log system, e.g. OpenSearch, it make sense to turn off the dev mode, so the format will be json - which is simpler to process as structured fields
Use the btp chart with custom values I'll set manager.logger_use_dev_mode to false, so the log will be created in json format
Feel free to construct the checklist with whatever items seem most reasonable for your change. You could disassemble the Implementation part to even smaller separate checklist items if you're working on something big for example. But do …
> feat: support customization for logger dev mode

- Dockerfile
- api/common/utils/secret_template.go
- internal/config/config.go
- main.go
- sapbtp-operator-charts/templates/deployment.yml
changing the cluster id of an existing cluster can cause unexpected behavior and malfunctioning of the operator.
Therefore in the case cluster id is changed the operator will fail to start until reverted to initial cluster id
> block cluster id change

- controllers/servicebinding_controller.go
- controllers/servicebinding_controller_test.go
- controllers/serviceinstance_controller.go
> ignore transient error during polling

- api/common/consts.go
- controllers/servicebinding_controller.go
- internal/config/config.go
- main.go
- sapbtp-operator-charts/templates/configmap.yml
- sapbtp-operator-charts/templates/secret.yml
- sapbtp-operator-charts/values.yaml
This feature is disabled by default, it should be enabled when btp opeartor is crashing due to OOM during startup that is caused in cluster that has many secrets/configmaps.
it is the user's responsibility to label the relevant secrets/configmaps with the needed label:
"services.cloud.sap.com/managed-by-sap-btp-operator": "true
> OOM due to secrets/configmaps - limited cache implementation

- controllers/servicebinding_controller.go
binding should use the secret that was used for the instance creation
> bug fix - cross namespace resources

- api/common/consts.go
- main.go
- sapbtp-operator-charts/templates/pre-delete-job.yml
> Internal - delete cluster secret during undeploy

- config/crd/bases/services.cloud.sap.com_servicebindings.yaml
- config/crd/bases/services.cloud.sap.com_serviceinstances.yaml
- controllers/servicebinding_controller.go
- controllers/servicebinding_controller_test.go
- controllers/serviceinstance_controller.go
https://github.com/SAP/sap-btp-service-operator/issues/490
operator should not block binding creation as long instance is not being deleted or not provisioned
> Bug fix - create binding when instance update failed should be allowed

- README.md
> watchParametersFromChanges.md
